### ISSUE TITLE
Q-state Potts model incorrectly defined

### ISSUE THREAD

**Issue by borisdevos** [QuantumKitHub/MPSKitModels.jl#28]
The current ```potts_exchange``` and ```potts_field``` functions where $q$ is a parameter is defined in such a way that only $q=3$ is correct.
The Hamiltonian for the Q-state Potts model is
$$H = -\sum_{i=1}^L\sum_{k=1}^{Q-1} (JZ_i^\dagger Z_{i+1})^k + h X_i^k)$$,
with $Z$ and $X$ already correctly defined in ```potts_exchange``` and ```potts_field```.

**Comment by lkdvos** [comment]
Aren't these functions asserting that q = 3? I'm more than happy to add the other cases as well, but could you provide some things that I can test?

**Comment by lkdvos** [comment]
This was fixed in #29
