### ISSUE TITLE
Spin operators with U(1) symmetry

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [QuantumKitHub/MPSKitModels.jl#37]
I notice that the $S_z$ operator with spin 1/2 and U(1) symmetry `S_z(U1Irrep)` is constructed as
```
TensorMap(Rep[U₁](1/2=>1, -1/2=>1) ← Rep[U₁](1/2=>1, -1/2=>1)):
* Data for sector (Irrep[U₁](1/2),) ← (Irrep[U₁](1/2),):
 -0.5 + 0.0im
* Data for sector (Irrep[U₁](-1/2),) ← (Irrep[U₁](-1/2),):
 0.5 + 0.0im
```
Naively thinking, the element corresponding to U1Irrep(±1/2) should be ±0.5. May I ask why you make the opposite choice?

**Comment by lkdvos** [comment]
This seems to be an error in our implementation... ☹️  I just checked the other operators, and it seems like indeed, our raising and lowering operators `S_plus` and `S_min` are also backwards:

```julia
julia> sp = S_plus(U1Irrep)
TensorMap(Rep[U₁](1/2=>1, -1/2=>1) ← (Rep[U₁](1/2=>1, -1/2=>1) ⊗ Rep[U₁](-1=>1))):
* Data for sector (Irrep[U₁](-1/2),) ← (Irrep[U₁](1/2), Irrep[U₁](-1)):
[:, :, 1] =
 1.0 + 0.0im


julia> sm = S_min(U1Irrep)
TensorMap(Rep[U₁](1/2=>1, -1/2=>1) ← (Rep[U₁](1/2=>1, -1/2=>1) ⊗ Rep[U₁](1=>1))):
* Data for sector (Irrep[U₁](1/2),) ← (Irrep[U₁](-1/2), Irrep[U₁](1)):
[:, :, 1] =
 1.0 + 0.0im
```

I will try and get this fixed
